### ISSUE TITLE
eIAM Onboarding for Visualize

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1366]
**Tasks / DoD**

- [ ] Describe our current dev environment (i.e. TEST) in the GitLab Wiki 
- [ ] Provide authentication redirect URI(s) to Thomas Immer
- [ ] Call with Abraxas, BIT, BAFU und IXT (04.03.2024)
